### ISSUE TITLE
Some environment has timestamp related error with add method

### ISSUE THREAD

**Issue by KishiTheMechanic** [elsoul/skeet-firestore#57]
Only skeet-solana-mobile template web front end has this issue.
https://github.com/elsoul/skeet-solana-mobile-stack/issues/47

skeet functions + add method from @skeet-framework/firestore didn't work suddenly.
Before it worked well. (This repository didn't updated for this moment thought)

Also asking for Firebase support team.

```
>  Error: Error adding document: Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "rme" (found in field "createdAt"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
>      at Poa (/Users/ktm/dev/skeet-solana-mobile-stack/functions/skeet/dist/index.js:1324:711)
>      at /Users/ktm/dev/skeet-solana-mobile-stack/functions/skeet/dist/index.js:1353:1058
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async runFunction (/Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:506:9)
>      at async runHTTPS (/Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:531:5)
>      at async /Users/ktm/dev/skeet-solana-mobile-stack/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:694:21
```

**Comment by KishiTheMechanic** [comment]
For now, this is the way to use

https://github.com/firebase/firebase-functions/issues/1496
